#scene three
label scene_three:

    "Biting cold is the first thing I feel when I wake up. Unsurprisingly, the fire died down overnight. I rub my face, clearing the bleariness from my eyes. It is only then I see the documents strewn about around me."
    "Not an unfamiliar situation to wake up to, but the location certainly is unique."
    "The blizzard still rages on, I can tell that much from the window. Not much else to discern. I can barely see my van through the haze."
    "I’m still good on supplies for another day or so, so my only hope is that the blizzard subsides by then."
    "For now, I suppose there’s not much else to do besides check on the werebeast. He should be fine, but there’s much I would like to ask him."
    # [scene transition]
    em "Good morning. Would you care to join me for breakfast?"
    "The werebeast stirs, and turns to look at me."
    wb "You’re persistent."
    em "Ha, you could call it that. You are also the only company I have while I am here."
    wb "Fair enough. I can’t say I’ll be good company."
    em "Good enough for me. Now, breakfast?"
    "We eat breakfast in silence, though it’s not an uncomfortable one."
    "However, once I finish cleaning up, only then does the werebeast speak up."
    wb "I did kill all of the other prisoners down here, if that’s what you were wondering."
    "I was taken aback, mostly due to how unprompted the confession was."
    em "I—"
    wb "Does that satisfy your question?"
    em "Not exactly. Mind elaborating?"
    wb "We realized pretty quickly that the estate was abandoned when no one came down to feed us. We couldn’t escape either, since the magic keeping the prisons locked was still pretty strong."
    wb "So everyone started getting worried about how they were going to survive. You should have seen how quick they were willing to turn to cannibalism. It was disgusting."
    wb "Anyway, I ate all of them. It’s not like I wasn’t getting hungry myself. I couldn’t stand another minute with any of them, and I didn’t want them to stick around long enough that I started to pity them."
    em "You speak about them with contempt. You must despise these people."
    wb "Hah. That’s an understatement."
    wb "I found a perverse enjoyment in watching them suffer."
    wb "They were vile people. I wasn’t their only victim, but I took the worst of it because I fought back."
    wb "I could never fit into the mould they were trying to shape me into. I’m glad they met the end that they had."
    em "…"
    em "You were the one to curse all of them, were you?"
    wb "Quick on the uptake. Yes, I was. That’s why I’m like this as well."
    "Magic lingers from where it is cast. As it goes, it’s wise to use some other object to channel magic through, rather than channeling the magic through one’s own body. A horror story children would be told when they first start learning magic is when a man died from essentially cooking himself alive from frequently using fire magic from his hands and mouth."
    "This would explain the cocktail nature of the werebeast’s curse, and why the conditions of how it works are not so clear-cut. The lingering magic from cursing every person eventually built up to be its own fully fledged curse, rather than be some minor inconvenience."
    em "Why didn’t you use a conduit? You don’t seem the type to use magic in such a risky way without reason."
    wb "You know that it’s easy to trace magic from its source. Much like the ballistics of a gun."
    wb "I learned it’s much harder to trace when you use your own body to channel magic."
    wb "It worked, didn’t it? They never did figure out who was behind all of the cursings."
    em "That’s…novel."
    wb "You’d be surprised how many ideas you get from listening to the radio. I wasn’t allowed to listen to it when I was younger, but I snuck one in my room, and I would listen to it when I had the chance."
    em "You weren’t allowed the radio?"
    wb "I wasn’t allowed many things, Good Doctor. Even as an adult I could not act as my own person."
    wb "The only time I was allowed to leave the house was to meet with a man who fancied me, arranged by my parents."
    wb "I cursed him too, by the way."
    "I continued to urge him to talk about his past life, and he spoke about it with nothing but disdain and contempt."
    "I begin to realize that his actions were one of desperation, and an attempt to sieze control of his life."
    "I pour him a cup of tea I had prepared while we were talking, and he holds it awkwardly in his large claws."
    em "I have one more thing to ask."
    wb "Not like I can object."
    em "You can. I am being quite nosy after all. However you seem eager to tell your story."
    wb "...Anyway, what did you want to ask?"
    em "Why haven’t you left this place? As you can see, the magic locking this prison has long since faded. You are free to leave whenever you want. You could sieze the life you always wanted."
    wb "As horrid of a life mine has been, my actions aren’t completely excusable. There’s no better fate for me than to rot in this cell."
    wb "It’s not like I have anywhere else to go, nor do I have any aspirations that are feasible for me."
    wb "I have nothing here. I have less out there."
    "The werebeast pours himself another cup of tea. The thought leaves my mouth faster than I can think on it."
    em "Why not come travel with me?"
    "As impulsive as the offer was, it was one I was welcoming of. For the first time during this stay, the Werebeast is astonished, and it takes him a moment to respond."
    wb "What?"
    em "I am a traveling doctor. I do have one other person that will soon travel with me, however neither of us would mind an additional companion to join us. We have the means to support an extra occupant or two."
    em "If you wanted a fresh start with no one to judge you, why not in a strange land with some strangers?"
    wb "How...bold."
    wb "And dangerous. You know what I’ve done. What makes you think I wont stop at just that?"
    em "Have I done anything to draw your ire?"
    wb "What if you will? I could leave my past behind, but if youre here, wouldn’t it be important to consider how I could harm you?"
    em "Maybe so. But it has been quite some time. You can take this as an opportunity to be someone beyond their agony and vengence. You could be your own person."
    "The werebeast doesn’t respond. He puts down his cup, and I collect it from him."
    em "I’ll give you time to consider the idea. You’re not obligated to choose one way or another, and I would be fine with whatever you decide."
    "I stand up and ascend the stairs."
    em "I will return in the evening to check up on your wounds. My hope is that theyre healing fine."
    return
